services:
  database:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_DB=gift_intake
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
